### ISSUE TITLE
Replace PNG Icons with SVG or Custom Painted Icons

### ISSUE THREAD

**Issue by cshannon3** [MHCI2021/book_reader_app#18]
Icons to Add 
- Back Arrow
- Book Store
- Library
- Profile
- Bookmark
- List
- FontSize button
...
<img width="238" alt="Screen Shot 2020-08-08 at 10 55 41 AM" src="https://user-images.githubusercontent.com/33521708/89713468-d368b380-d965-11ea-9cce-6b425c1c588d.png">
<img width="342" alt="Screen Shot 2020-08-08 at 10 55 20 AM" src="https://user-images.githubusercontent.com/33521708/89713469-d5327700-d965-11ea-8b85-5ff87a581f9e.png">
<img width="356" alt="Screen Shot 2020-08-08 at 10 55 00 AM" src="https://user-images.githubusercontent.com/33521708/89713472-d6fc3a80-d965-11ea-9009-11caa1a68fd7.png">

**Comment by janellewen** [comment]
[Icons.zip](https://github.com/MHCI2021/book_reader_app/files/5046627/Icons.zip)

Might have more after creating the font adjustment overlay but here are the ones we have so far!

**Comment by cshannon3** [comment]
Can either use an [icon generator](https://pub.dev/packages/fluttericon/install) to convert svg to font icons
Or parse the svg path myself using old code similar to [svg path generator](https://flutterawesome.com/a-flutter-library-for-gradually-painting-svg-path-objects-on-canvas/)
or use one from online libraries using [this package](https://pub.dev/packages/flutter_icons)
